org: firsttracksolutiontechnologies
app: jupiterxpress
service: jupiterXpress

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  stage: api
  environment:
    AWS_ACCESS_KEY_ID_ : ${env:AWS_ACCESS_KEY_ID_}
    AWS_REGION_ : ${env:AWS_REGION_}
    AWS_SECRET_ACCESS_KEY_ : ${env:AWS_SECRET_ACCESS_KEY_}
    CONTACT_EMAIL : ${env:CONTACT_EMAIL}
    CONTACT_SERVICE_EMAIL : ${env:CONTACT_SERVICE_EMAIL}
    DB_HOST : ${env:DB_HOST}
    DB_NAME : ${env:DB_NAME}
    DB_PASSWORD : ${env:DB_PASSWORD}
    DB_USER : ${env:DB_USER}
    DELHIVERY_10KG_SURFACE_KEY : ${env:DELHIVERY_10KG_SURFACE_KEY}
    DELHIVERY_500GM_SURFACE_KEY : ${env:DELHIVERY_500GM_SURFACE_KEY}
    EMAIL_HOST : ${env:EMAIL_HOST}
    EMAIL_PASS : ${env:EMAIL_PASS}
    EMAIL_PORT : ${env:EMAIL_PORT}
    EMAIL_SECURE : ${env:EMAIL_SECURE}
    EMAIL_USER : ${env:EMAIL_USER}
    JWT_SECRET : ${env:JWT_SECRET}
    MOVIN_ACCOUNT_NUMBER : ${env:MOVIN_ACCOUNT_NUMBER}
    MOVIN_CLIENT_ID : ${env:MOVIN_CLIENT_ID}
    MOVIN_CLIENT_SECRET : ${env:MOVIN_CLIENT_SECRET}
    MOVIN_SERVER_ID : ${env:MOVIN_SERVER_ID}
    MOVIN_SUBSCRIPTION_KEY : ${env:MOVIN_SUBSCRIPTION_KEY}
    MOVIN_TENANT_ID : ${env:MOVIN_TENANT_ID}
    RAZORPAY_KEY_SECRET : ${env:RAZORPAY_KEY_SECRET}
    S3_BUCKET_NAME_ : ${env:S3_BUCKET_NAME_}
    VERIFY_EMAIL : ${env:VERIFY_EMAIL}
    PICKRR_CLIENT_ID : ${env:SHIPROCKET_CLIENT_ID}
    PICKRR_REFRESH_TOKEN : ${env:SHIPROCKET_REFRESH_TOKEN}
    DILLIKING_SECRET_KEY : ${env:DILLIKING_SECRET_KEY}
functions:
  app:
    handler: app.handler
    memorySize: 512
    timeout: 30
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true
plugins:
  - serverless-plugin-split-stacks
  - serverless-offline
  - serverless-dotenv-plugin